name: Connexion SSH à Alwaysdata

on:
  push:
    branches:
      - main  # Ou toute autre branche de ton choix

jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out du code
        uses: actions/checkout@v2

      - name: Connexion SSH avec le serveur Alwaysdata
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.abbouda }}.alwaysdata.net"
          username: ${{ secrets.abbouda }}  # Remplace par ton nom d'utilisateur GitHub (par exemple, "abbouda")
          key: ${{ secrets.SSH_KEY }}  # Utilise le secret contenant ta clé privée SSH
          script: |
            cd $HOME/www/  # Change le répertoire si nécessaire, ou ajoute d'autres commandes à exécuter sur ton serveur
